name: Build & Push Snippet Image - dev
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  call-cd-prod:
    uses: IngsisPrintScript/workflows-and-actions/.github/workflows/deploy.yaml@main
    with:
      java-version: "21"
      environment: "development"
      service_name: "authentication"
      image_route: "ghcr.io/ingsisprintscript/users-authentication:dev"
    secrets: inherit

